const products = [
  {
    id: 1,
    category: "jacket",
    name: "Mens Winter Leathers Jackets",
    price: 48.0,
    priceOriginal: 75.0,
    imageDefault: "/assets/img/products/jacket-3.jpg",
    imageHover: "/assets/img/products/jacket-4.jpg",
  },
  {
    id: 2,
    category: "shirt",
    name: "Pure Garment Dyed Cotton Shirt",
    price: 45.0,
    priceOriginal: 56.0,
    imageDefault: "/assets/img/products/shirt-1.jpg",
    imageHover: "/assets/img/products/shirt-2.jpg",
  },
  {
    id: 3,
    category: "jacket",
    name: "MEN Yarn Fleece Full-Zip Jacket",
    price: 58.0,
    priceOriginal: 65.0,
    imageDefault: "/assets/img/products/jacket-5.jpg",
    imageHover: "/assets/img/products/jacket-6.jpg",
  },
  {
    id: 4,
    category: "skirt",
    name: "Black Floral Wrap Midi Skirt",
    price: 25.0,
    priceOriginal: 35.0,
    imageDefault: "/assets/img/products/clothes-3.jpg",
    imageHover: "/assets/img/products/clothes-4.jpg",
  },
  {
    id: 5,
    category: "casual",
    name: "Casual Men's Brown shoes",
    price: 99.0,
    priceOriginal: 105.0,
    imageDefault: "/assets/img/products/shoe-2.jpg",
    imageHover: "/assets/img/products/shoe-2_1.jpg",
  },
  {
    id: 6,
    category: "watches",
    name: "Pocket Watch Leather Pouch",
    price: 150.0,
    priceOriginal: 170.0,
    imageDefault: "/assets/img/products/watch-3.jpg",
    imageHover: "/assets/img/products/watch-4.jpg",
  },
  {
    id: 7,
    category: "watches",
    name: "Smart watche Vital Plus",
    price: 100.0,
    priceOriginal: 120.0,
    imageDefault: "/assets/img/products/watch-1.jpg",
    imageHover: "/assets/img/products/watch-2.jpg",
  },
  {
    id: 8,
    category: "party wear",
    name: "Womens Party Wear Shoes",
    price: 25.0,
    priceOriginal: 30.0,
    imageDefault: "/assets/img/products/party-wear-1.jpg",
    imageHover: "/assets/img/products/party-wear-2.jpg",
  },
  {
    id: 9,
    category: "jacket",
    name: "Mens Winter Leathers Jackets",
    price: 32.0,
    priceOriginal: 45.0,
    imageDefault: "/assets/img/products/jacket-1.jpg",
    imageHover: "/assets/img/products/jacket-2.jpg",
  },
  {
    id: 10,
    category: "sports",
    name: "Trekking & Running Shoes - black",
    price: 58.0,
    priceOriginal: 64.0,
    imageDefault: "/assets/img/products/sports-2.jpg",
    imageHover: "/assets/img/products/sports-4.jpg",
  },
  {
    id: 11,
    category: "formal",
    name: "Men's Leather Formal Wear shoes",
    price: 50.0,
    priceOriginal: 65.0,
    imageDefault: "/assets/img/products/shoe-1.jpg",
    imageHover: "/assets/img/products/shoe-1_1.jpg",
  },
  {
    id: 12,
    category: "shorts",
    name: "Better Basics French Terry Sweatshorts",
    price: 78.0,
    priceOriginal: 85.0,
    imageDefault: "/assets/img/products/shorts-1.jpg",
    imageHover: "/assets/img/products/shorts-2.jpg",
  },
];

export default products;
